name: UD-MLOps CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest black

    - name: Lint with pylint
      run: |
        pylint **/*.py

    - name: Format with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest -v
